# ===== Server =====
server.port=${PORT:8081}

spring.application.name=auth-service

# ===== PostgreSQL =====
spring.datasource.url=${DBURL:jdbc:postgresql://localhost:5433/careerpilot}
spring.datasource.username=${DBUSERNAME:postgres}
spring.datasource.password=${DBPASSWORD:careerpilot}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=auth
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# ===== Flyway =====
spring.flyway.enabled=true
spring.flyway.default-schema=auth
spring.flyway.schemas=auth
spring.flyway.create-schemas=true
spring.flyway.locations=classpath:db/migration

# ===== JWT =====
app.jwt.secret=${JWT_SECRET:change-this-to-a-long-random-base64-secret-in-every-environment}
app.jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION_MS:86400000}
app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}

# ===== Actuator =====
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

# ===== Logging =====
logging.level.com.careerpilot=DEBUG
